spring:
  application:
    name: NyeoreumnagiBatch

  datasource:
    url: jdbc:h2:mem:batchtest;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always

