spring:
  profiles:
    active: local

  application:
    name: Nyeoreumnagi

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./batchdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
