version: '3'

services:

  web:
    container_name: nyeoreumnagi-blue
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRED_IN=${ACCESS_TOKEN_EXPIRED_IN}

networks:
  app-network:
    external: true