version: '3'

services:

  web:
    container_name: nyeoreumnagi-blue
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul

networks:
  app-network:
    external: true