name: Close issues on PR merge into fe or be

on:
  pull_request:
    types: [closed]
    branches: [fe, be]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Get source branch name
        id: check-branch
        run: echo "SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Close linked issues if branch pattern matches
        if: |
          (startsWith(steps.check-branch.outputs.SOURCE_BRANCH, 'feat/fe') && github.event.pull_request.base.ref == 'fe') ||
          (startsWith(steps.check-branch.outputs.SOURCE_BRANCH, 'fix/fe') && github.event.pull_request.base.ref == 'fe') ||
          (startsWith(steps.check-branch.outputs.SOURCE_BRANCH, 'feat/be') && github.event.pull_request.base.ref == 'be') ||
          (startsWith(steps.check-branch.outputs.SOURCE_BRANCH, 'fix/be') && github.event.pull_request.base.ref == 'be')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            (async () => {
              const prBody = context.payload.pull_request.body || '';
              const issueRegex = /\b(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*[:\-]?\s*#(\d+)/gi;
              let match;

              while ((match = issueRegex.exec(prBody)) !== null) {
                const issueNumber = Number(match[1]);
                console.log(`Closing issue #${issueNumber}`);
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed'
                });
              }
            })();
